version: '3.7'
services:
  jenkins:
    build:
      context: .
    image: jenkins-casc
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - "./jenkins.yaml:/usr/share/jenkins/ref/jenkins.yaml"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/usr/bin/docker:/usr/bin/docker"
